# config.make generated by configure script
MERCURY_CONFIG =Linux
MERCURY_BASE =/home/mercury/projects/Mercury
MERCURY_BUILD=/home/mercury/projects/Mercury/build
MERCURY_FLAGS =
export MERCURY_CONFIG
export MERCURY_BASE
export MERCURY_BUILD
export MERCURY_FLAGS
