/*
 * unp.h
 *
 *  Created on: Aug 28, 2016
 *      Author: mercury
 */

#ifndef UNP_H_
#define UNP_H_

#include "config.h"	/* configuration options for current OS */
					/* "config.h" is generated by configure */

#include <sys/types.h>	/* basic system data types */
#include <sys/socket.h>	/* basic socket definitions */
#if TIME_WITH_SYS_TIME
#include <sys/time.h>	/* timeval{} for select() */
#include <time.h>		/* timespec{} for pselect() */
#else
#if HAVE_SYS_TIME_H
#include <sys/time.h>	/* includes <time.h> unsafely */
#else
#include <time.h>		/* old system? */
#endif
#endif
#include <netinet/in.h>	/* sockaddr_in{} and other Internet definitions */
#include <arpa/inet.h>	/* inet(3) functions */
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>



#endif /* UNP_H_ */
